### ISSUE TITLE
Does foreman support different stop signals?

### ISSUE THREAD

**Issue by localshred** [ddollar/foreman#118]
In my appraisal of foreman I've LOVED everything except my uncertainty in how processes are stopped via signals. It appears that processes are only stopped by SIGKILL or SIGTERM. This seems unhelpful in certain circumstances where I know a certain signal will gracefully stop a process (e.g. QUIT for Resque). For certain processes SIGTERM or SIGKILL will likely be appropriate, but how can we handle cases where we know of a different signal that will be more beneficial?

Does foreman already support this? If I export to upstart, would foreman be able to dictate to upstart the shutdown signal to use? Apologies for not having this be a proper issue/feature request and no code attached, just not sure any other way to have these questions addressed. Thanks for your time.

**Comment by andrew-carroll** [comment]
That wiki page doesn't address whether foreman is able to specify a kill signal when exporting to upstart.
