### ISSUE TITLE
Foreman doesn't produce output

### ISSUE THREAD

**Issue by azare** [ddollar/foreman#159]
When I run 'foreman start' my NodeJS process is started but I do not receive any output to the console.  Shouldn't output be directed to the console?

**Comment by Xavdidtheshadow** [comment]
Hey, so I'm seeing this issue with node. 

`npm start` has output, but a procfile with `web: npm start` doesn't. 

```
$ node --version
v0.10.32
$ gem list|grep foreman
foreman (0.78.0)
$ npm -v
2.1.3
```
