### ISSUE TITLE
Foreman is ignoring the PORT environment variable.

### ISSUE THREAD

**Issue by c4ftabrez** [ddollar/foreman#167]
Hi 
I want the foreman gem to use the PORT value provided in the my development env file instead of using its own values. My files setup is shown below:
1. A bash script to start foreman:
   
   foreman start -e development.env
2. The development.env file content:
   
   PORT=3000
3. The Procfile content
   
   web: bundle exec rails server thin -p $PORT -e $RAILS_ENV $1

The dev server ends up starting on port 5000.  I know I can start foreman with --p 3000 to force it to use that port.  But that defeats the purpose of the env file.

Any suggestions?

**Comment by colllin** [comment]
Here's a solution I found based on http://stackoverflow.com/a/2013589/361609 :

```
nf start -p ${PORT:-3000} dev-server=1,dev-client=1
```

This uses an external PORT environment variable if available, or defaults to 3000.  If that command is aliased to `npm start`, then it allows you to run with like `PORT=4000 npm start`, and it will pick up your desired port.
