### ISSUE TITLE
How to specify environment?

### ISSUE THREAD

**Issue by clifff** [ddollar/foreman#17]
I have started using Foreman in my app, and it's been great so far. I was wondering if there is a way to specify a RAILS_ENV as a paraemter inside Procfile? For example,  when I start a delayed_job worker on production, I have to use:

```
RAILS_ENV=production script/delayed_job start
```

How can I access/set RAiLS_ENV within procfile?

**Comment by chrishough** [comment]
has anyone got this to work with RAILS_ENV=development ?

**Comment by stoplion** [comment]
For commands that need to override variables in `.env` is is possible to set them inline. For example in the case @chrishough points out above `RAILS_ENV=development`.

`RAILS_ENV=test bundle exec foreman start`   
always runs in development for me
