### ISSUE TITLE
foreman doesn't respect commands with grep

### ISSUE THREAD

**Issue by josh-m-sharpe** [ddollar/foreman#198]
$ gem list | grep foreman
foreman (0.46.0)

This works:
redislog: redis-cli MONITOR
(shows all traffic to redis)

This doesn't work:
redislog: redis-cli MONITOR | grep -v resque
(show all traffic to redis, grep out things from resque)

This doesn't work:
Procfile:
redislog: ./script/redis_log
script/redis_log:
# !/bin/bash

redis-cli MONITOR | grep -v resque

... so I believe this is some conflict between foreman and grep, or bash, or something.  Everything I remove grep everything is peachy.

Also, foreman otherwise rocks my face.  Thanks!

**Comment by hackeron** [comment]
Writing a script doesn't help either.

in my Procfile
```
log: bash script/taillog.sh
```

In my bash script:
```sh
tail -f log/development.log | grep -v Moped
```

When I do "foreman start" my terminal emulator's title is "grep" and I see no log output :( - any ideas?
