### ISSUE TITLE
Foreman is unstoppable if started from a script

### ISSUE THREAD

**Issue by ariofrio** [ddollar/foreman#235]
Say you have a Procfile:

```
web: nc -l $PORT
```

And a script `run`:

```
#!/bin/bash
foreman start & echo $!
```

If we start foreman using the script, and try to send it a Ctrl-C, Foreman will be unable to kill its children:

```
$ ./run
21906
14:20:50 web.1  | started with pid 21907
$ kill -s INT 21906
SIGINT received
14:21:29 system | sending SIGTERM to all processes
14:21:34 system | sending SIGKILL to all processes
$ ps -A | grep nc
21907 pts/4    00:00:00 nc
```

**Comment by alexch** [comment]
I'm having success running foreman from inside [rerun](http://github.com/alexch/rerun). In this case, foreman is in the foreground, but it still has a parent process that wants to control it by sending it a graceful quit signal. The trick is that your parent script needs to be smart enough to pass the quit signal on to foreman. In my tests foreman responds nicely to either INT or QUIT signals.
