### ISSUE TITLE
Foreman isn't using the current version of Ruby (it's using 1.8.7)

### ISSUE THREAD

**Issue by scottmessinger** [ddollar/foreman#257]
I'm using RVM and am using Ruby version 1.9.3p194.

``` shell
$ ruby -v
ruby 1.9.3p194 (2012-04-20 revision 35410) [x86_64-darwin11.4.0]
```

Here's my Procfile

``` shell
$ cat Procfile
web: bundle exec unicorn -p $PORT -c ./config/unicorn.rb
```

Here's the error message I get

``` shell
$ foreman start
19:40:40 web.1  | started with pid 35870
19:40:40 web.1  | /Users/ScottMessinger/.rvm/gems/ruby-1.9.3-p194@mygemset/gems/bundler-1.2.0.rc.2/lib/bundler/definition.rb:364:in `validate_ruby!': Your Ruby version is 1.8.7, but your Gemfile specified 1.9.3 (Bundler::RubyVersionMismatch)
19:40:40 web.1  |   from /Users/ScottMessinger/.rvm/gems/ruby-1.9.3-p194@mygemset/gems/bundler-1.2.0.rc.2/lib/bundler.rb:112:in `setup'
19:40:40 web.1  |   from /Users/ScottMessinger/.rvm/gems/ruby-1.9.3-p194@mygemset/gems/bundler-1.2.0.rc.2/lib/bundler/setup.rb:17
19:40:40 web.1  | exited with code 1
19:40:40 system | sending SIGTERM to all processes
SIGTERM received
```

**Comment by sayotte** [comment]
Seeing this (or something similar) with 0.77.0, using rbenv w/ 1.9.3-p551:

    [vagrant]$ /usr/local/rbenv/versions/1.9.3-p551/bin/ruby /usr/bin/foreman start
    18:18:34 web.1  | started with pid 9083
    18:18:34 web.1  | /home/vagrant/.gem/ruby/1.9.1/gems/bundler-1.7.11/lib/bundler/definition.rb:380:in `validate_ruby!': Your Ruby version is 1.8.7, but your Gemfile specified 1.9.3 (Bundler::RubyVersionMismatch)
    18:18:34 web.1  |       from /home/vagrant/.gem/ruby/1.9.1/gems/bundler-1.7.11/lib/bundler.rb:118:in `setup'
    18:18:34 web.1  |       from /home/vagrant/.gem/ruby/1.9.1/gems/bundler-1.7.11/lib/bundler/setup.rb:17
    18:18:34 web.1  | exited with code 1
    18:18:34 system | sending SIGTERM to all processes

I'm not sure why it'd be finding the 1.8.7 interpreter:

    [vagrant]$ ruby -v
    ruby 1.9.3p551 (2014-11-13 revision 48407) [x86_64-linux]
    [vagrant]$ rbenv version
    1.9.3-p551 (set by RBENV_VERSION environment variable)
    [vagrant]$ which ruby
    ~/.rbenv/shims/ruby

Frustratingly, if I modify the Gemfile to specify 1.8.7, I get this:

    [vagrant]$ /usr/local/rbenv/versions/1.9.3-p551/bin/ruby /usr/bin/foreman start
    18:24:12 web.1  | started with pid 9188
    18:24:12 web.1  | Your Ruby version is 1.9.3, but your Gemfile specified 1.8.7
    18:24:12 web.1  | exited with code 18
    18:24:12 system | sending SIGTERM to all processes

**Comment by sayotte** [comment]
Apologies, this was with 0.63.0, not 0.77.0... there I was seeing another bug where Process.spawn doesn't appear to be defined.

**Comment by sayotte** [comment]
This appears to rightly be a problem with something other than foreman (other posters encountered it with both rbenv and rvm; rbenv said it was bundler, bundler said it was user error, and so on). This looked like a good lead: https://github.com/bundler/bundler/issues/2489

I ultimately overcame it by putting /usr/local/rbenv/versions/1.9.3-p551/bin in my PATH before even the rbenv shim directories.

Anyway, not a foreman issue, sorry for thread necromancy.
