### ISSUE TITLE
Foreman starts using 100% of the CPU in an eternal loop consuming nil data from the process output

### ISSUE THREAD

**Issue by mauricio** [ddollar/foreman#260]
I'm running foreman at the following environment:
- Mac OS lion
- terminal + oh-my-zsh
- ruby 1.9.3

When running a bunch of processes (in this case, MySQL, ElasticSearch and a Rails app) foreman goes up to consume 100% of the CPU in an eternal loop trying to grab the output of the running processes. After a bit of profiling I have found out the source of the issue, the `watch_for_output` loop at the `Foreman::Engine` class. In my machine, it was eternally consuming nil's from the process and kept on running on it forever.

I ended up changing it to sleep a bit if none of the processes produced any kind of output, but I'm not sure if this is the correct solution.

Maybe having a separate thread for each process would be better or trying to find a way to grab this output in an async way instead of being synchronous.

Here's my change (it isn't a pull request because i'm not sure if this is the correct solution, but it works on my machine now and foreman isn't at 100% of CPU anymore):

``` ruby
  def watch_for_output
    Thread.new do
      begin
        loop do
          wrote_data = false
          (IO.select(@readers.values).first || []).each do |reader|
            data = reader.gets
            wrote_data = !data.nil?
            output_with_mutex name_for(@readers.invert[reader]), data
          end
          sleep(1) unless wrote_data
        end
      rescue Exception => ex
        puts ex.message
        puts ex.backtrace
      end
    end
  end
```

**Comment by sebs** [comment]
2017 and I have something like this, blocking a process on my devbox.
