### ISSUE TITLE
Foreman doesn't start -   terminated by SIGTERM

### ISSUE THREAD

**Issue by tokhi** [ddollar/foreman#314]
I just want to start the foreman but I get this:

foreman start
16:46:30 cacapi.1  | started with pid 14149
16:46:30 cmsapi.1  | started with pid 14151
16:46:30 elapi.1   | started with pid 14153
16:46:30 es.1      | started with pid 14155
16:46:30 casc.1    | started with pid 14157
16:46:30 cdnmgmt.1 | started with pid 14159
16:46:30 cdnmgmt.1 | /home/vagrant/.rvm/gems/ruby-1.9.2-p180/gems/foreman-0.61.0/bin/foreman-runner: line 41: /home/vagrant/cdn-management/bin/thin: No such file or directory
16:46:30 cdnmgmt.1 | exited with code 1
16:46:30 system    | sending SIGTERM to all processes
SIGTERM received
16:46:30 cacapi.1  | terminated by SIGTERM
16:46:30 cmsapi.1  | terminated by SIGTERM
16:46:30 elapi.1   | terminated by SIGTERM
16:46:30 es.1      | terminated by SIGTERM
16:46:30 casc.1    | terminated by SIGTERM

Anyone has already experienced this? Thanks.

**Comment by HilDavis** [comment]
When I start foreman start i got following

15:01:02 console.1  | started with pid 13446
15:01:02 solr.1     | started with pid 13448
15:01:02 nginx.1    | started with pid 13451
15:01:02 frontend.1 | started with pid 13455
15:01:02 sidekiq.1  | started with pid 13458
15:01:02 nginx.1    | nginx: [emerg] open() "/run/nginx.pid" failed (13: Permission denied)
15:01:02 nginx.1    | exited with code 1
15:01:02 system     | sending SIGTERM to all processes
15:01:02 solr.1     | terminated by SIGTERM
15:01:02 console.1  | terminated by SIGTERM
15:01:02 frontend.1 | terminated by SIGTERM
15:01:02 sidekiq.1  | terminated by SIGTERM
nr-ubuntu@nrubuntu-desktop:~/Desktop/CoreCommerce$ sudo touch /run/nginx.pid nr-ubuntu@nrubuntu-desktop:~/Desktop/CoreCommerce$ sudo chmod -R 777 /run/nginx.pid
nr-ubuntu@nrubuntu-desktop:~/Desktop/CoreCommerce$ foreman start
15:02:55 console.1  | started with pid 13567
15:02:55 solr.1     | started with pid 13569
15:02:55 nginx.1    | started with pid 13572
15:02:55 frontend.1 | started with pid 13576
15:02:55 sidekiq.1  | started with pid 13578
15:02:57 console.1  | [13570] Puma starting in cluster mode...
15:02:57 console.1  | [13570] * Version 2.15.3 (ruby 2.1.2-p95), codename: Autumn Arbor Airbrush
15:02:57 console.1  | [13570] * Min threads: 0, max threads: 16
15:02:57 console.1  | [13570] * Environment: development
15:02:57 console.1  | [13570] * Process workers: 4
15:02:57 console.1  | [13570] * Phased restart available
15:02:57 console.1  | [13570] * Listening on tcp://0.0.0.0:3000
15:02:57 console.1  | /home/nr-ubuntu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/puma-2.15.3/lib/puma/binder.rb:234:in `initialize': Address already in use - bind(2) for "0.0.0.0" port 3000 (Errno::EADDRINUSE)
15:02:57 console.1  | 	from /home/nr-ubuntu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/puma-2.15.3/lib/puma/binder.rb:234:in `new'
15:02:57 console.1  | 	from /home/nr-ubuntu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/puma-2.15.3/lib/puma/binder.rb:234:in `add_tcp_listener'
15:02:57 console.1  | 	from /home/nr-ubuntu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/puma-2.15.3/lib/puma/binder.rb:98:in `block in parse'
15:02:57 console.1  | 	from /home/nr-ubuntu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/puma-2.15.3/lib/puma/binder.rb:84:in `each'
15:02:57 console.1  | 	from /home/nr-ubuntu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/puma-2.15.3/lib/puma/binder.rb:84:in `parse'
15:02:57 console.1  | 	from /home/nr-ubuntu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/puma-2.15.3/lib/puma/cluster.rb:328:in `run'
15:02:57 console.1  | 	from /home/nr-ubuntu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/puma-2.15.3/lib/puma/cli.rb:215:in `run'
15:02:57 console.1  | 	from /home/nr-ubuntu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/puma-2.15.3/bin/puma:10:in `<top (required)>'
15:02:57 console.1  | 	from /home/nr-ubuntu/.rbenv/versions/2.1.2/bin/puma:23:in `load'
15:02:57 console.1  | 	from /home/nr-ubuntu/.rbenv/versions/2.1.2/bin/puma:23:in `<main>'
15:02:57 console.1  | exited with code 1
15:02:57 system     | sending SIGTERM to all processes
15:02:57 solr.1     | terminated by SIGTERM
15:02:57 nginx.1    | terminated by SIGTERM
15:02:57 frontend.1 | terminated by SIGTERM
15:02:57 sidekiq.1  | terminated by SIGTERM
 Anybody Please help me??

**Comment by willianra** [comment]
how can you solved that?
i have the same errror
