### ISSUE TITLE
Separate, development-only Procfile

### ISSUE THREAD

**Issue by jt2190** [ddollar/foreman#358]
We're using Foreman to start our node.js app in development. We've encountered a recurring  problem: **Developers accidentally check in changes they made to the `Procfile` for development purposes**, which results in the wrong processes starting in Heroku.

Specifically, our devs would like to start their MongoDB and Redis processes with the rest of the app when developing, so they modify the Procfile. If they're in a hurry or forgetful, the `Procfile` changes end up in production.

To work around this issue, I've implemented a number of `bin/` scripts as [suggested by this comment](https://github.com/ddollar/foreman/issues/12#issuecomment-2656011) to conditionally start processes only if `$NODE_ENV=development`. This does help protect the `Procfile` from accidental changes, and it does help us keep the right things running in production, but our production Heroku app dashboard now has "memento" of a Redis and MongoDB process that were started then immediately exited.

![heroku-dashboard-with-non-running-mementos3](https://f.cloud.github.com/assets/897048/449035/f2b07fd6-b265-11e2-90da-0687d6886d46.png)

[I've asked the Heroku team](https://help.heroku.com/tickets/83803) if they could try to start their Celadon Cedar stack with something other than the default `Procfile`. For example, if they could try to start with `Procfile-heroku` first, and then fall back to `Procfile` if that file is not found. They suggested that I file this as an issue with Foreman. I don't understand how changing Foreman will help with this issue, however, I'm writing it up here and perhaps someone can give me some insight.

**Comment by codyrobbins** [comment]
I wish this could be revisited—the fact that both Heroku and Foreman use a file called `Procfile` that I need to have different things in is really annoying. I use Foreman to start all the service dependencies for an app, like Redis and the Resque dashboard, in development, but do not want processes for many of them in production on Heroku.

Did `Procfile` originate with Foreman in the first place or was it a pre-existing standard for listing processes from an earlier tool? In an ideal world for me, `Procfile` would actually be a Yaml file with top-level keys for environments just like the Rails `config/database.yml` database configuration file:

```
production: &production
  rails: bundle exec rails server
  resque: bundle exec rails resque:work QUEUE=*
development: &development
  <<: *production
  redis: redis-server
  resque_dashboard: bundle exec resque-web --foreground --no-launch
test: *development
```
