### ISSUE TITLE
unicorn does not start

### ISSUE THREAD

**Issue by ghost** [ddollar/foreman#37]
I am running unicorn 3.6.2 and foreman 0.18.0 as follows

web: bundle exec unicorn -p $PORT -c config/unicorn.rb 

instead I get this 
/.rvm/gems/ruby-1.9.2-p180/gems/foreman-0.18.0/lib/foreman/engine.rb:49:in `block in processes_in_order': undefined method`[]' for nil:NilClass (NoMethodError

config/unicorn.rb has the following

worker_processes  4 
timeout          40

**Comment by wimnorder** [comment]
+1 for @JuanitoFatas - Thank you! ;)

**Comment by ocolot** [comment]
+1 for @JuanitoFatas
