### ISSUE TITLE
Procfile order?

### ISSUE THREAD

**Issue by prayerslayer** [ddollar/foreman#392]
Is there something as order-dependence in Procfiles? If it is and I just missed it in the docs, please ignore this issue. If it's not, please read on.

I have a node.js server, a MongoDB and Redis which I start with foreman. My Procfile looks like this:

```
mongo: mongod
redis: redis-server
web: nodemon app.js
```

In my environment configuration I specifiy a port for node to listen on.

```
PORT=3000
```

The relevant app.js code:

```
app.listen( process.env.PORT );
```

Using `foreman start -e local.env` node should run on port 3000, right? It does not, instead it runs on PORT + 200 (3200 in this case). Long story short the solution was to put node first in my Procfile.

```
web: nodemon app.js
mongo: mongod
redis: redis-server
```

I tested it with foreman 0.60 and 0.63, same behavior. Is this expected?

**Comment by ghostsquad** [comment]
I'd love to see this implemented. Maybe something like what https://github.com/jwilder/dockerize does?
