### ISSUE TITLE
Error performing export when `$HOME` is unset.

### ISSUE THREAD

**Issue by phemmer** [ddollar/foreman#402]
```
lib/foreman/export/base.rb:121:in `expand_path': couldn't find HOME environment -- expanding `~' (ArgumentError)
```

Which in my version is this line: https://github.com/ddollar/foreman/blob/1905a7c310ded5f9ffab9b8911d9795d7924697d/lib/foreman/export/base.rb#L121

Many automated utilities strip `$HOME` out of the environment (in this case puppet), and so the export cannot be performed. The `$HOME` variable could be forged, but I think foreman should gracefully handle it's absence.

**Comment by bwbaugh** [comment]
Still seeing this issue on v0.78.0.
