### ISSUE TITLE
$PORT and process.env.PORT offset by 100

### ISSUE THREAD

**Issue by ghost** [ddollar/foreman#418]
I'm starting a couple processes with Foreman.  In my node.js process, I refer to `process.env.PORT`. In my Procfile, I use `$PORT` as a parameter to another process. My second process is only for debugging and basically processes some files and opens up my browser to the specified port (it's not using the port for anything else). So if I start Foreman with `foreman start --port=5000`, `process.env.PORT` is 5100 while `$PORT` is 5000. Shouldn't these be the same value?

**Comment by RichardOrnelas** [comment]
I just now started to get this issue. i request port `8080` and foreman starts with `8180`
