### ISSUE TITLE
foreman exits immediately

### ISSUE THREAD

**Issue by tkral** [ddollar/foreman#42]
Hi,

I'm playing around with foreman to use it in my development process.  When I use it to export to upstart, everything seems to be working just fine:

root@tkral-wsl:~/dev/samples/dataloader[develop]$ foreman export upstart /etc/init --user tkral
[foreman export] cleaning up: /etc/init/dataloader-web-1.conf
[foreman export] cleaning up: /etc/init/dataloader-web.conf
[foreman export] cleaning up: /etc/init/dataloader.conf
[foreman export] writing: /etc/init/dataloader.conf
[foreman export] writing: /etc/init/dataloader-web.conf
[foreman export] writing: /etc/init/dataloader-web-1.conf
root@tkral-wsl:~/dev/samples/dataloader[develop]$ start dataloader
dataloader start/running
root@tkral-wsl:~/dev/samples/dataloader[develop]$ status dataloader
dataloader start/running

However, when I use foreman start, the child process is exiting immediately:

root@tkral-wsl:~/dev/samples/dataloader[develop]$ foreman start
11:07:10 web.1     | started with pid 20780
11:07:10 web.1     | process exiting
11:07:10 web.1     | process terminated
11:07:10 system    | sending SIGTERM to all processes

I'm a newbie when it comes to Ruby so I'm not sure if I have everything setup correctly (especially with PTY).  Is there any way for me to test my environment or at least get more information to try to debug this?

Thanks.
-Tim

**Comment by nikhilbhavsar5895** [comment]
Hi i am also getting same issue 
14:25:38 server.1   | started with pid 14836
14:25:38 frontend.1 | started with pid 14837
14:25:38 server.1   | 2020/08/12 14:25:38 mmap: bad file descriptor
14:25:38 server.1   | exited with code 1
14:25:38 system     | sending SIGTERM to all processes
14:25:38 frontend.1 | terminated by SIGTERM

My procfile contains
server: bee run -downdoc=true -gendoc=true  -e=frontend -e=conf -e=logs -e=datastructs -e=filters -e=grifts -e=out -e=inp -e=database -e=events -e=tasks -e=templates
frontend: cd frontend && npm run dev

**Comment by tzipisheinin** [comment]
> It seems like the program is terminating immediately with no output when running under foreman.

Is this issue still happening? 
My `Procfile.https` look like this:
`web: thin start --ssl --ssl-key-file server.key --ssl-cert-file server.crt  --port 3000
redis: redis-server
worker: bundle exec rake resque:work QUEUE='*'
scheduler: bundle exec rake resque:scheduler
guard: guard -P livereload`
and I just find out that running the first command - `web` using `forman start -f Procfile.https`
doesn't show the errors of this command, but when I run this line alone in terminal - I can see the exact errors.
Does foreman hiding the errors, or maybe he doesn't even get those errors from his child commands
