### ISSUE TITLE
`foreman run` not setting .env env vars before Rails initializers execute?

### ISSUE THREAD

**Issue by odigity** [ddollar/foreman#434]
Took me three hours to debug this problem.  Finally got an answer when I put some code in the config/initializers/ file I was having trouble with which wrote the value of the env var to a file to prove what it contained at the time.

Here are the scenarios I have documented:

1) `foreman start` -- Everything behaves correctly.  Variables defined in .env are loaded and present by the time both config/_.yml files are parsed and config/initializers/_.rb files are executed.

2) `foreman run env|grep VARX` -- Behaves correctly, shows the value of VARX from the .env file.

3) `foreman run rails console` -- The env vars are present by the time you can enter commands on the console, but they were _not_ present at the time the initializers ran.

Using forman v0.63.0 on Ubuntu 12.04 with Ruby 2.1.1 and Rails 4.1.0.rc1.

**Comment by rossdakin** [comment]
http://stackoverflow.com/questions/25938847/why-are-my-rails-initializers-caching-env-variables-in-the-console-foreman-dev

**Comment by odigity** [comment]
You don't negotiate with the devil.

**Comment by emcmanus** [comment]
Thanks @odigity @rossdakin @gabu
