### ISSUE TITLE
SIGTERM not properly forwarded to node process

### ISSUE THREAD

**Issue by buffpojken** [ddollar/foreman#440]
It seems like foreman is not properly forwarding signals to a running node-process. 

Processes are started by the following Procfile: 

```
rabbitmq: rabbitmq-server start
web: bundle exec rails s
node: node node/server.js
redis: redis-server /usr/local/etc/redis.conf
```

and starts as expected. 

With the the Node-app, the following signal-trap is installed: 

```
process.on('SIGTERM', function() {
  console.log('Received Signal');
    process.exit(1);
});
```

and is invoked as expected when running Node straight from the commandline (when bound on SIGINT). However, when running via foreman - no signal of any kind is propagated.

I've tried to read through the code for a hint but as far as I can see - the signals should be forwarded? 

_Testing was done on OS X 10.9.2_

**Comment by causztic** [comment]
still an issue even on the latest version.

when a process fails and SIGTERM is sent to the other node processes:
`11:51:28 system            | sending SIGTERM to all processes` is shown but the other node processes did not receive the SIGTERM.

I manually patched this by:
- making foreman run a shell script instead
- use `trap 'lsof -ti :8080 | xargs kill -15' EXIT` to manually pass a SIGTERM signal to the corresponding process

**Comment by domenkozar** [comment]
I observe the same behavior, looking at the code https://github.com/ddollar/foreman/blob/1445adc429d79b5b3dd1d54cf9dcb75d253c924f/lib/foreman/engine.rb#L192 should print that the signal is being sent but I haven't seen it.
