### ISSUE TITLE
Upstart export is no executing command with rbenv path of owned user

### ISSUE THREAD

**Issue by wireframe** [ddollar/foreman#443]
Upgrading to latest version of foreman broke the generated upstart configuration files and upstart is reporting the following error now when trying to start the application server:

```
/bin/sh: 1: exec: bundle: not found
```

My Procfile:

``` ruby
web: bundle exec puma -p $PORT
```

My Environment: 
- vagrant VM
- ubuntu 12.04
- rbenv

This regression introduced by commit c039f379ff1b6eb87673aa73a3548ba20d1722e4 as part of #438.  Using `setuid <%= user %>` does not seem to inherit the proper user `PATH` required for rbenv to execute the target binary.  The previous version used `exec su - <%= user %>` which properly inherited rbenv on the path.

**Comment by x2es** [comment]
good to have `foreman export -e HOME=/my/home`
otherwise I have to produce exess artefacts

**Comment by djch** [comment]
Hello — I'm hoping someone here can help. I'm using Foreman 0.84.0 on Debian 9. 

The systemd config I'm exporting seems to ignore the environment configuration and fails with the same error as @wireframe: `/bin/bash: line 0: exec: bundle: not found`.

Export command:
```bash
sudo env "PATH=$PATH" foreman export systemd -a fishwife -u dan -m web=1,release=0,worker=0 /etc/systemd/system/
```

Resulting config file (/etc/systemd/system/fishwife-web@.service)
```
[Unit]
PartOf=fishwife-web.target

[Service]
User=dan
WorkingDirectory=/home/dan/fishwife
Environment=PORT=%i
Environment="PATH=/home/dan/.rbenv/plugins/ruby-build/bin:/home/dan/.rbenv/shims:/home/dan/.rbenv/bin:/home/dan/.rbenv/plugins/ruby-build/bin:/home/dan/.rbenv/shims:/home/dan/.rbenv/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games"
Environment="RAILS_SERVE_STATIC_FILES=enabled"
Environment="RAILS_ENV=production"
Environment="RAILS_MASTER_KEY=redacted"
Environment="DATABASE_URL=redacted"
Environment="SHELL=/bin/bash"
Environment="HOME=/home/dan"
ExecStart=/bin/bash -lc 'bundle exec puma -C config/puma.rb'
Restart=always
StandardInput=null
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=%n
KillMode=mixed
TimeoutStopSec=5
```

**Comment by djch** [comment]
Okay so, if I change `ExecStart=` to use `/bin/bash -c` instead of `/bin/bash -lc`, it works.

How come the generator adds `-l` to bash, and why wouldn't that that be compatible with the rest of my config?

(I think Foreman is rad and would really like to use the `export` function on this project if possible).
