### ISSUE TITLE
foreman not behaving with grep

### ISSUE THREAD

**Issue by ryanjafari** [ddollar/foreman#462]
I experience this exact issue using foreman 0.71.0:

https://github.com/ddollar/foreman/issues/198

Thanks for foreman!

**Comment by hackeron** [comment]
Writing a script doesn't help either.

in my Procfile

```
log: bash script/taillog.sh
```

In my bash script:

```sh
tail -f log/development.log | grep -v Moped
```
When I do "foreman start" my terminal emulator's title is "grep" and I see no log output :( - any ideas?

**Comment by bbugh** [comment]
This is still happening for me with foreman 0.84.0. Did anyone ever figure out a workaround for this?
