### ISSUE TITLE
Remove dotenv dependency

### ISSUE THREAD

**Issue by allaire** [ddollar/foreman#505]
Remember you told in a PR that you were going to remove the dotenv dependency in order to stop all the versioning hell. Is this going to happen?

**Comment by npearson72** [comment]
I noticed the merged pr. Not sure I understand the vendor path either. Does this mean foreman will no longer require dotenv? Can I use figaro or some other env variable solution?

**Comment by victorbrender** [comment]
Just a heads up, the merged pr was on the forked version of the gem, not this one.

**Comment by npearson72** [comment]
@victorbrender Got it, thanks. So now that it's not a dependency, does that mean foreman (in your fork) will not automatically look in the .env file?

**Comment by victorbrender** [comment]
@npearson72  It won't. But I really advise against using the forked version of the gem. Instead maybe renaming the folder or using an alternative gem as you already suggested would work best.

**Comment by walro** [comment]
Would be nice to have this solves, since dotenv recently released released 2.0.0, making bundler resolve to an old version of foreman (0.63.0), unless you lock against an older version of dotenv.
