### ISSUE TITLE
nohup foreman leaves processes hanging after -SIGINT

### ISSUE THREAD

**Issue by haggen** [ddollar/foreman#508]
So, I setup a Procfile and used this script to run foreman in background:

```
nohup foreman > app.log 2>&1 &; 
echo $! > app.pid
```

Then, when I want to halt the processes I just do `kill -SIGINT $(cat app.pid)`. This kills foreman and the direct child `sh` processes that -- I presume -- `bundle exec` started, but Puma and Sidekiq are left running.

Any thoughts ?

**Comment by ddollar** [comment]
Would it be possible to boil this down into a reproducible test case repo so I can investigate?

**Comment by sb8244** [comment]
Sidekiq doesn't daemonize unless you pass `-d` to it. https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/cli.rb#L277

**Comment by virtualfunction** [comment]
Do you think it's the bundle exec running the process as a child that's happening, like #94 
I found I had to remove bundle exec

**Comment by aripollak** [comment]
This does seem related to #94. I am able to reproduce this on Linux with the following Procfile:
`sidekiq: bundle exec sidekiq $TEST`

With $TEST (sidekiq process is left around, and is unkillable without -9):
```
^CSIGINT received
13:51:37 system    | sending SIGTERM to all processes
13:51:37 sidekiq.1 | terminated by SIGTERM
```

Without $TEST (sidekiq process terminates correctly):
```
^CSIGINT received
13:51:09 system    | sending SIGTERM to all processes
13:51:11 sidekiq.1 | exited with code 0
```

If I remove the `$TEST`, it works fine. If I use this Procfile instead, it works fine:
`sidekiq: exec bundle exec sidekiq $TEST`

**Comment by MauPalantir** [comment]
I experienced a similar issue with a simple Procfile like

[other services]
api: rackup --env=api_dev -p 9292
 
with a very basic Sinatra app. When foreman stops (whether I kill it by Ctrl+C or it stops running after an error), the child web server processes don’t (the other services are stopped as expected).

**Comment by juanibiapina** [comment]
I have a process that calls "foreman start" as a child.

After killling foreman, the web process keeps running, but changes pid (o.O)!!.

Might be related to this.

**Comment by ezjacob-maheim** [comment]
@ddollar I think this is the same issue I'm having. I've setup a sample repo with simple parent and child scripts here https://github.com/ezjacob-maheim/foreman-issue

If you run
```
bundle exec foreman start
```
and then look at the process tree using pstree you'll see something like this
```
-+- 34251 ejacob /bin/bash ./parent.sh
 \-+- 34252 ejacob /bin/bash ./child.sh
   \--- 36087 ejacob sleep 1
```
when you exit using Ctrl+C. Everything terminates all the way through the process tree. I confirmed by using ps -ef

Now when you pass foreman start to the background
```
bundle exec foreman start &
```
the pstree is like this
```
-+= 60852 ejacob foreman: master  
 \-+- 61141 ejacob /bin/bash ./parent.sh
   \-+- 61142 ejacob /bin/bash ./child.sh
     \--- 61991 ejacob sleep 1
```
when I run kill on the foreman root process the output from foreman is simliar
```
SIGTERM received
sending SIGTERM to all processes
terminated by SIGTERM
```

but if you look at the child process in ps you'll see that its parent pid is now 1
```
61142     1   0  6:20PM ttys006    0:00.12 /bin/bash ./child.sh
```

**Comment by ddollar** [comment]
If anyone that is being affected by this would like to submit a PR I would be grateful. Thank you! My time is currently quite limited so I will likely not be addressing non-critical issues for quite some time.
