### ISSUE TITLE
-t undocumented on man page

### ISSUE THREAD

**Issue by sb8244** [ddollar/foreman#510]
Timeout flag is not documented on the man page. I saw the PR and the option after digging around source, but it was a bit confusing knowing if the functionality existed or not.

**Comment by ddollar** [comment]
Thanks for submitting an issue. Would you be interested in putting together a pull request to fix it?

**Comment by sb8244** [comment]
Sure thing!

I'm looking at the `foreman.1.ronn` file now. However, I noticed that the .ronn file is 7 months last commit wheras `foreman.1` file is 19 hours. Which one should be updated to reflect the changes?

**Comment by ddollar** [comment]
Update the .ronn file. The man page gets refreshed during every release.
