### ISSUE TITLE
Foreman Gemfile Installation Problem

### ISSUE THREAD

**Issue by kirby510** [ddollar/foreman#512]
I have a problem when I try to install foreman to run the .env in my rails application. Below is the command that I entered in Terminal. Can I know how I should install foreman on the application which is using Rails 4.1.1 and Ruby 2.1.2? 

➜  fci_fyp_system  gem install foreman
Successfully installed foreman-0.77.0
Parsing documentation for foreman-0.77.0
Done installing documentation for foreman after 1 seconds
1 gem installed
➜  fci_fyp_system  bundle install
Using rake 10.4.2
Using i18n 0.6.11
Using json 1.8.1
Using minitest 5.4.3
Using thread_safe 0.3.4
Using tzinfo 1.2.2
Using activesupport 4.1.1
Using builder 3.2.2
Using erubis 2.7.0
Using actionview 4.1.1
Using rack 1.5.2
Using rack-test 0.6.2
Using actionpack 4.1.1
Using mime-types 1.25.1
Using polyglot 0.3.5
Using treetop 1.4.15
Using mail 2.5.4
Using actionmailer 4.1.1
Using activemodel 4.1.1
Using arel 5.0.1.20140414130214
Using activerecord 4.1.1
Using execjs 2.2.2
Using autoprefixer-rails 4.0.1.1
Using sass 3.2.19
Using bootstrap-sass 3.3.1.0
Using coffee-script-source 1.8.0
Using coffee-script 2.3.0
Using thor 0.19.1
Using railties 4.1.1
Using coffee-rails 4.0.1
Using multipart-post 2.0.0
Using faraday 0.9.0
Using font-awesome-sass 4.2.2
Using hashie 3.3.2
Using hike 1.2.3
Using multi_json 1.10.1
Using jbuilder 2.2.5
Using jquery-rails 3.1.2
Using jwt 1.2.0
Using multi_xml 0.5.5
Using mysql2 0.3.17
Using oauth2 0.9.4
Using omniauth 1.2.2
Using omniauth-oauth2 1.1.2
Using bundler 1.6.2
Using tilt 1.4.1
Using sprockets 2.12.3
Using sprockets-rails 2.2.2
Using rails 4.1.1
Using rdoc 4.2.0
Using sass-rails 4.0.5
Using sdoc 0.4.1
Using so_auth 0.0.2
Using spring 1.2.0
Using turbolinks 2.5.3
Using uglifier 2.6.0
Your bundle is complete!
Use `bundle show [gemname]` to see where a bundled gem is installed.
➜  fci_fyp_system  bundle show foreman
Could not find gem 'foreman'.
➜  fci_fyp_system  foreman start
zsh: command not found: foreman
➜  fci_fyp_system

**Comment by ddollar** [comment]
Sorry I am unable to diagnose Bundler/Rubygems problems.
