### ISSUE TITLE
Line 125 in lib/foreman/export/base.rb blows up when $HOME is missing

### ISSUE THREAD

**Issue by gswallow** [ddollar/foreman#513]
During a Chef run, I run:

cd /opt/newrelic/plugins/tokumx ; bundle exec foreman export -a newrelic_tokumx_agent -u root upstart /etc/init

I assume this is in a non-login shell; $HOME isn't set.  When foreman tries to expand "~", it fails, and thus Chef fails.

**Comment by ddollar** [comment]
If anyone that is being affected by this would like to submit a PR I would be grateful. Thank you! My time is currently quite limited so I will likely not be addressing non-critical issues for quite some time.
