### ISSUE TITLE
Update custom signals wiki entry

### ISSUE THREAD

**Issue by phillbaker** [ddollar/foreman#514]
I didn't want to edit the [wiki entry](https://github.com/ddollar/foreman/wiki/Custom-Signals) directly, but I had to use a changed bash script to get things working with custom signals (in development on Mac OS X):

```
#!/bin/bash
# command to run
bin/daemon --foreground &

# capture PID
PID=$!

# trap TERM and change to something else
trap "echo killing $PID; kill -QUIT $PID; exit 0" SIGINT SIGTERM
echo "backgrounded in $PID"
wait
```

I can update the wiki entry as well if that'd be helpful.

**Comment by unmanbearpig** [comment]
Can you clarify what issues have you fixed and how did you do it? I see a few changes in your version, but not sure why you did them.

**Comment by ddollar** [comment]
If anyone that is being affected by this would like to submit a PR I would be grateful. Thank you! My time is currently quite limited so I will likely not be addressing non-critical issues for quite some time.
