### ISSUE TITLE
Confusing upstart issue

### ISSUE THREAD

**Issue by sb8244** [ddollar/foreman#516]
Hey David. I was moving a new app into production today with version 0.73.0. I got the following script under coordinator-coordinator-1.conf:

```
start on starting coordinator-coordinator
stop on stopping coordinator-coordinator
respawn

env PORT=5000

setuid deploy

chdir /srv/www/mailnext/current

exec bundle exec ernie -p 9496 -c config/ernie.cfg
```

This errors out badly every time, trying to execute under an entirely different ruby version. I know foreman upstart works because we use it on 5 other projects, so I took a look at their version (0.63.0) and I get this script:

```
start on starting coordinator-coordinator
stop on stopping coordinator-coordinator
respawn

exec su - deploy -c 'cd /srv/www/mailnext/current; export PORT=5000; bundle exec ernie -p 9496 -c config/ernie.cfg >> /srv/www/mailnext/shared/log/coordinator-1.log 2>&1'
```

This starts okay (albeit errors on my side :)). What is the big different between the scripts that would cause such different behavior?

**Comment by blelump** [comment]
Same problem here. This is really confusing since the new syntax works with older version of upstart (1.12 on board), whereas it actually doesn't. As stated [here][1], `setuid` is supported since version 1.4. 

I've spent a couple hours trying to manage to get it to work and finally surrendered and then downgraded to 0.64. 

[1]: http://upstart.ubuntu.com/cookbook/#setuid

**Comment by mikecarroll** [comment]
+1 one on this, also having issues with upstart after upgrading the gem

**Comment by ddollar** [comment]
If anyone that is being affected by this would like to submit a PR I would be grateful. Thank you! My time is currently quite limited so I will likely not be addressing non-critical issues for quite some time.

**Comment by ddollar** [comment]
Closing this for now but if anyone using Upstart has a fix to submit I would gladly accept a PR.
