### ISSUE TITLE
Feature Request: Add systemd export

### ISSUE THREAD

**Issue by ryansch** [ddollar/foreman#52]
Systemd is the new hotness in Fedora 15 and will eventually work into RHEL and variants.

**Comment by ioquatix** [comment]
Can someone explain or document how to use this? It isn't obvious what directories the script should be installed into.

**Comment by dgoradia-atlas** [comment]
+1 for @ioquatix's request. What should the location for systemd be?

**Comment by pwnall** [comment]
`/lib/systemd/system` works on both Ubuntu and Fedora.

**Comment by ioquatix** [comment]
I've been using `/etc/systemd/system` on Arch, is that the same?

**Comment by dgoradia-atlas** [comment]
I'm using EL 7 and I think @pwnall is correct. It is then symlinked to `/etc/systemd/system'. Thanks.

**Comment by jhass** [comment]
From systemd.unit(5):

```
       Table 1.  Load path when running in system mode (--system).
       ┌────────────────────────┬─────────────────────────────┐
       │Path                    │ Description                 │
       ├────────────────────────┼─────────────────────────────┤
       │/etc/systemd/system     │ Local configuration         │
       ├────────────────────────┼─────────────────────────────┤
       │/run/systemd/system     │ Runtime units               │
       ├────────────────────────┼─────────────────────────────┤
       │/usr/lib/systemd/system │ Units of installed packages │
       └────────────────────────┴─────────────────────────────┘
```

Custom units that aren't installed alongside a package are considered local configuration.

**Comment by pwnall** [comment]
@jhass Very cool, thank you!
