### ISSUE TITLE
Getting below error & even after googling, I am not able to solve this problem

### ISSUE THREAD

**Issue by theajaygupta** [ddollar/foreman#520]
C:\Sites\demo>foreman start
C:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/site_ruby/1.9.1/rubygems/custo
m_require.rb:36:in `require': cannot load such file -- foreman/cli (LoadError)
        from C:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/site_ruby/1.9.1/r
ubygems/custom_require.rb:36:in `require'
        from C:/Program Files (x86)/Heroku/bin/foreman:8:in `<main>'

C:\Sites\demo>

**Comment by jeshtan** [comment]
Hi i got the same problem, googling bring me to here. Any clues?

**Comment by theajaygupta** [comment]
Yes dear, I have solved this problem after doing re installation of rails, & Heroku under fresh direcory which has clean name without any special or white space characters!!

I used simple alphabetical characters for renaming directory name under which I am doing my heroku installation which solved my problem.

**Comment by andrea-ligios** [comment]
I'm getting this error too...

**Comment by theajaygupta** [comment]
Hi Andrea, Please check the installation of Heroku, Foreman does not work if your installation of Heroku has any special characters or spaces in any directory name or in directory Hierarchy.

Keep it like c:/Heroku (Valid to work with foreman)
Not like this c:/program files/ Heroku   (Not valid)

I hope this information will help you.

**Comment by andrea-ligios** [comment]
Thank you @theajaygupta , it definitely helped! I've open a Q&A on the problem, linking this page: http://stackoverflow.com/q/31243947/1654265

**Comment by gespejo** [comment]
Hi:
I installed heroku in the c:\Heroku directory but it's still not working. Can you help me?
Thanks
C:\>foreman
C:/Heroku/ruby-1.9.3/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `
require': cannot load such file -- foreman/cli (LoadError)
        from C:/Heroku/ruby-1.9.3/lib/ruby/site_ruby/1.9.1/rubygems/custom_requi
re.rb:36:in `require'
        from C:/Heroku/bin/foreman:8:in `<main>'

C:\>

**Comment by theajaygupta** [comment]
Dear @gespejo Please follow http://stackoverflow.com/q/31243947/1654265 Q&A on the problem created by @andrea-ligios so that everyone can get help from this Q & A.

**Comment by gespejo** [comment]
Ok ;)
