### ISSUE TITLE
No documentation as to the port distribution mechanism

### ISSUE THREAD

**Issue by andrewychoi** [ddollar/foreman#521]
Through trial and error I've found that `foreman` increments the port values that are given to each process by 100. Where in the documentation should this be noted? Is this something that's likely to change in future iterations of `foreman`?

**Comment by playpauseandstop** [comment]
Also is there any reasons why base port of foreman should be a multiple of 1000? This also should be documented, IMO

**Comment by andrewychoi** [comment]
As far as I can tell, there's no requirement. I'm currently running `foreman` with a base port of 7800 and I've been fine.

**Comment by playpauseandstop** [comment]
Strange. 

I'm not using foreman, but [honcho](https://github.com/nickstenning/honcho), its Python clone and looks like guys from honcho set up strict requirement for base port to be a multiple of 1000, https://github.com/nickstenning/honcho/issues/132

But if multiple requirement is not a requirement at all, documentation for ``foreman`` should be updated to prevent possible misunderstandings.

**Comment by raul** [comment]
I got bitten by this after sorting a `Procfile` (I was also confused by the fact that foreman adds 100 to each `PORT` in `foreman start` but not in `foreman run`).

Foreman's [announcement blog post](http://blog.daviddollar.org/2011/05/06/introducing-foreman.html) mentions this behavior - would you consider a PR adding a new section to the docs @ddollar ? In that case I'd be happy to send one.

**Comment by ddollar** [comment]
If anyone that is being affected by this would like to submit a PR I would be grateful. Thank you! My time is currently quite limited so I will likely not be addressing non-critical issues for quite some time.

**Comment by ddollar** [comment]
Closing this issue for now but would happily accept a PR with a docs change addressing this. Thanks!
