### ISSUE TITLE
runit export should empty /env directory before writing out variables

### ISSUE THREAD

**Issue by bensomers** [ddollar/foreman#534]
Title is fairly self-explanatory. The runit exporter takes the current environment variables, and writes them into each process's /env directory (per runit standard). Each environment variable gets its own file. However, if we have environment variables around from a previous export, they will still stick around, contaminating the environment of our app. (Since they're each in their own file, foreman isn't doing anything to blow them away.

If the patch sounds good, I can implement it and PR. Looks like it's just a one-liner in export/runit.rb.

**Comment by ddollar** [comment]
If anyone that is being affected by this would like to submit a PR I would be grateful. Thank you! My time is currently quite limited so I will likely not be addressing non-critical issues for quite some time.

**Comment by bensomers** [comment]
I'll take a look - hopefully I can figure out what the one-liner I had in mind was :).

**Comment by ddollar** [comment]
Closing for now as this bug has gotten quite old but please feel free to comment / send in a PR for your proposed change.
