### ISSUE TITLE
Does foreman require dotenv?

### ISSUE THREAD

**Issue by npearson72** [ddollar/foreman#538]
I have a .env directory (not file) in the root of my app. It's not related to the dotenv gem. When trying to run foreman, I get a conflict as it seems to expect .env to be a file.

Is there a way around this?

**Comment by jarinudom** [comment]
Just a note: dotenv just hit 2.0.0 so unless you specify a lower version of dotenv, bundler is resolving it to use foreman 0.63.0.

**Comment by npearson72** [comment]
So are you saying foreman will not look for a .env file? Because that's what I'm asking here.
