### ISSUE TITLE
Sidekiq does not die with Ctrl-C on foreman

### ISSUE THREAD

**Issue by sonots** [ddollar/foreman#553]
Procfile

```
test1: bundle exec sidekiq -q test1
test2: bundle exec sidekiq -q test2
test3: bundle exec sidekiq -q test3
```

MyWorker.rb

```
class MyWorker
  include Sidekiq::Worker
  sidekiq_options retry: false

  def perform(params)
    Sidekiq.logger.info { "start" }
    sleep 10
    Sidekiq.logger.info { "finish" }
  end
end
```

reproduce:

```
$ bundle exec rails c
rails> Sidekiq::Client.enqueue_to('test1', MyWorker, 'foo')
```

then, Ctrl-C on foreman

```
$ bundle exec foreman s
(omit)
01:18:58 test1.1 | 2015-04-22T16:18:58.954Z 8101 TID-otp6bh2ho INFO: Starting processing, hit Ctrl-C to stop
01:19:24 test1.1 | 2015-04-22T16:19:24.574Z 8101 TID-otolbbd84 MyWorker JID-ba53c839c56c5cdb53578efe INFO: start
01:19:24 test1.1 | 2015-04-22T16:19:24.574Z 8101 TID-otolbbd84 MyWorker JID-ba53c839c56c5cdb53578efe INFO: start
^CSIGINT received
01:19:27 system  | sending SIGTERM to all processes
01:19:28 test3.1 | exited with code 0
```

ps. one of three processes survived this time

```
$ ps -ef | grep sidekiq
sonots      7169     1  1 01:13 pts/6    00:00:04 sidekiq 3.3.4 argus [0 of 25 busy]
```

**Comment by sonots** [comment]
It seems this is caused because `foreman` does not wait until all of its children dies.

**Comment by sonots** [comment]
Issued to sidekiq, too https://github.com/mperham/sidekiq/issues/2312

**Comment by mperham** [comment]
Sidekiq does not die immediately upon Ctrl-C, it can take up to the shutdown timeout in seconds (default is 8 sec).  How long does Foreman wait for child processes?

**Comment by sonots** [comment]
It looked foreman does not wait at all cuurently, i.e., sends TERM and exit immediately.

Waiting 10 seconds as default would be sufficient like heroku waits 10 seconds.

**Comment by jfelchner** [comment]
I'm running into this too.  Foreman should definitely wait until all the children are finished before exiting.  Doesn't seem like leaving before your workers leave is something that a foreman would do. :wink:

**Comment by mcbridejc** [comment]
+1! I've hit this issue too. Running foreman via upstart, and everytime the service is restarted we get a new sidekiq worker.

**Comment by n-rodriguez** [comment]
I've made this patch for my use : https://github.com/jbox-web/deploy-it/commit/f5fed452d4885b7a91bf8984588aca760ba8a1ba, it seems to do the trick.

**Comment by ddollar** [comment]
Should be fixed now
