### ISSUE TITLE
Curl fails w/Foreman

### ISSUE THREAD

**Issue by pbraswell** [ddollar/foreman#558]
Hey David,
Peter (from Heroku),
I've got a strange issue.  When I use curl http:/localhost:7000 while running foreman, I get a connection refused error.  If I run web brick and try the same (http://localhost:3000) curl works just fine.

What would account for this.  And FYI, I have verified that I can reach http://localhost:7000 via a browser.  

TIA,
Peter

**Comment by ddollar** [comment]
Foreman does not actually do any networking other than picking port numbers so your problem is likely with the app or your network.

**Comment by moonhouse** [comment]
Peter, I had the same issue on my Mac running Yosemite while connecting from curl to Unicorn or Puma started by Foreman. 

After removing "fe80::1%lo0" from my /etc/hosts file as suggested by an answer on http://superuser.com/questions/830920/curl-local-host-names-on-mac-os-x-yosemite it worked for me. In my case it wasn't Foreman's fault. (So this comment is by no means an attempt to open this issue again.)
