### ISSUE TITLE
Install says it succeeds, but fails on OS X 10.11 El Capitan

### ISSUE THREAD

**Issue by tjsail33** [ddollar/foreman#567]
$ sudo gem install foreman
Password:
Successfully installed foreman-0.78.0
Parsing documentation for foreman-0.78.0
1 gem installed

$ type "foreman"
-bash: foreman: command not found

Tried installing via the pkg, but got a message saying installation failed and to contact the software manufacturer for assistance.

Any thoughts?

**Comment by ReneMoraales** [comment]
@tjsail33 found any solutions?

**Comment by tjsail33** [comment]
The issue stems from the new "Rootless" security that 10.11 includes, which disables writing to locations that many package managers use. "Rootless" can be disabled on your machine by running `sudo nvram boot-args="rootless=0"` and then rebooting. After you install the packages, I recommend re-enabling rootless by running `sudo nvram boot-args="rootless=1"` to utilize the security benefits it offers.

**Comment by randallb** [comment]
FWIW it fails even if you are in rootless mode.

**Comment by tjsail33** [comment]
Works fine for me after disabling rootless.

**Comment by randallb** [comment]
the command for disabling rootless has changed since the beta.

https://forums.developer.apple.com/thread/3981

**Comment by randallb** [comment]
It's because foreman is put in /usr/bin fwiw. Moving it to /usr/local or opt or something would fix.

**Comment by lifwanian** [comment]
/usr/local didn't work for me, /opt did though. Would I want /opt or /usr/local/opt?

For anyone looking for the command: `sudo cp -r /usr/local/foreman /opt`
