### ISSUE TITLE
Color on why: "Ruby users should take care not to install foreman in their project's Gemfile"

### ISSUE THREAD

**Issue by justin808** [ddollar/foreman#573]
@ddollar Any links or explanation on why

> Ruby users should take care not to install foreman in their project's Gemfile

I've got some projects with and some without foreman in the Gemfile. 

How urgent is it to remove foreman from the Gemfiles? How much of a problem does it cause? What kind of problems?

**Comment by allaire** [comment]
This is not really an issue anymore @justin808. It was back in the days when Foreman had a dependency on dotenv, the project kept being in version conflict. @ddollar simply removed the dependency and rolled his own dotenv-like feature.

@ddollar maybe we could remove this message in the README now and avoid confusions like these?

**Comment by cesc1989** [comment]
+1

**Comment by panozzaj** [comment]
I was also a little confused by this message, so I made a PR to delete the offending text in the README.

**Comment by justin808** [comment]
Any update on this one?

**Comment by ddollar** [comment]
Please install foreman at the system level and use it as a general development tool. Getting it into the mix of your dependencies in your Gemfile is unsupported.

**Comment by sbc100** [comment]
@ddollar can you explain why?  I thought that the `development` section of a Gemfile was the right place to install dev tools (I've used it for other tools such as `rubocop` `reek` `spring` `brakeman` and `bummr` without any issues).  What is wrong with doing this?
