### ISSUE TITLE
Foreman Export Upstart creates duplicated PORT env

### ISSUE THREAD

**Issue by stevendaniels** [ddollar/foreman#574]
Foreman's export sets the PORT env incorrectly when both the PORT is present in .env and concurrency > 1 is used in the export command.

Here's a [reproduction of the issue](https://github.com/stevendaniels/foreman_export_duplicate_port_issue), along with a possible fix. Putting the foreman-generated port last (after the contents of the .env file) allows services with concurrency to operate properly.

This issue extends beyond upstart exports. All templates that put the port before the env variables is probably affected. With the current template, when you run this command:
```
foreman export -a service -u me -e .env upstart . -c web=2
```

you end up with configurations like this:

```
start on starting service-web
stop on stopping service-web
respawn

env PORT=6000
env PORT='6000'

setuid me
...
```

```
#service-web-2.conf
start on starting service-web
stop on stopping service-web
respawn

env PORT=6001
env PORT='6000'
...
```

Obviously, starting such a service doesn't work well, the second instance tries to bind to port 6000, which is already in use.

**Comment by ddollar** [comment]
If you have a fix please consider submitting a PR. Thanks!

**Comment by ddollar** [comment]
Closing for now but please feel free to submit a PR with your fix. Thanks!
