### ISSUE TITLE
No process output on Windows: read would block

### ISSUE THREAD

**Issue by keritaf** [ddollar/foreman#575]
Platform: Windows 7 SP 1
Ruby: 2.2.2p95 (RubyInstaller)

When running ```foreman start``` I get processes running but no output for any of them. Foreman output is:
```
d:\work\exonit\sync2>foreman start -c main=2
A non-blocking socket operation could not be completed immediately. - read would block
D:/soft/Ruby22/lib/ruby/gems/2.2.0/gems/foreman-0.78.0/lib/foreman/engine.rb:373:in `read_nonblock'
D:/soft/Ruby22/lib/ruby/gems/2.2.0/gems/foreman-0.78.0/lib/foreman/engine.rb:373:in `read_self_pipe'
D:/soft/Ruby22/lib/ruby/gems/2.2.0/gems/foreman-0.78.0/lib/foreman/engine.rb:402:in `block (2 levels) in watch_for_output'
D:/soft/Ruby22/lib/ruby/gems/2.2.0/gems/foreman-0.78.0/lib/foreman/engine.rb:400:in `loop'
D:/soft/Ruby22/lib/ruby/gems/2.2.0/gems/foreman-0.78.0/lib/foreman/engine.rb:400:in `block in watch_for_output'
15:32:49 main.1 | exited with code 130
15:32:49 system | sending SIGKILL to all processes
15:32:49 system | sending SIGKILL to main.2 at pid 9920
15:32:49 main.2 | exited with code 0
Завершить выполнение пакетного файла [Y(да)/N(нет)]? y
```

Non-blocking read is not supported for pipes on Windows. `read_noblock` throws `Errno::EWOULDBLOCK` which is not handled in `read_self_pipe`, but `Errno::EAGAIN` is handled there - maybe forgot to handle? See http://www.gnu.org/savannah-checkouts/gnu/libc/manual/html_node/Error-Codes.html on EWOULDBLOCK and EAGAIN.

**Comment by Benjamin-Dobell** [comment]
There are output issues on OS X too (also Ruby 2.2.2). I'm working on a patch now.

**Comment by Benjamin-Dobell** [comment]
@keritaf Could you please try this:
https://github.com/ddollar/foreman/pull/594

It should address your issue and other related issues.
