### ISSUE TITLE
Specify default Procfile through environment variable?

### ISSUE THREAD

**Issue by olalonde** [ddollar/foreman#578]
Would be nice if I could add this to my `.zshrc` and foreman would just always use `Procfile.dev` without having to always specify it as an argument:

```
PROCFILE=Procfile.dev
```

More generally, would it be possible to make foreman behave differently depending on a `FOREMAN_ENV` variable? (e.g. `FOREMAN_ENV=staging` should use `Procfile.staging` and `.staging.env`)

**Comment by andrew-carroll** [comment]
Why not just make it a function?
```bash
foreman_with_env() {
  foreman "$@" $(if [ -n "$PROCFILE" ]; then echo "-f=$PROCFILE"; fi)
}
alias foreman=foreman_with_env
```

**Comment by olalonde** [comment]
Yep that would work... My bash skills are limited so thanks for the script :+1: .

**Comment by andrew-carroll** [comment]
No problem. After thinking about this more however, I agree with your original suggestion; being able to use environment variables as default behavior would be nicer. I'll poke around the code a bit later and if I can add the feature, I'll submit a PR.

**Comment by olalonde** [comment]
Has this feature been added?
