### ISSUE TITLE
Specify Upstart "kill signal" when exporting

### ISSUE THREAD

**Issue by andrew-carroll** [ddollar/foreman#579]
Currently, when exporting, there is no way to specify which [kill signal](http://upstart.ubuntu.com/cookbook/#kill-signal) Upstart should use when stopping a job; it has to be manually added after.

I'm at a loss, however, regarding how exactly to specify it. Adding it to the Procfile sounds like it would complicate its parsing. Any ideas?

**Comment by ddollar** [comment]
You can specify your own templates during export where you could change the defaults around a bit.
