### ISSUE TITLE
Using ruby-debug when running rails through foreman

### ISSUE THREAD

**Issue by dunkstewart** [ddollar/foreman#58]
Apologies, if this is a silly question, I may be grasping at straws here considering the more typical use cases for foreman.

I've recently started using foreman to manage the processes in my development environment.  I'm happy with the setup, it allows me to run rails, sphinx, and delayed job together and kill them all without forgetting about one of them.

However, putting a "debugger" breakpoint in my ruby code and starting a debug console is a problem with this setup.  The breakpoint does get hit because the web request hangs waiting to continue, but there is no interactive debug console on the foreman terminal.

Is it possible to get an interactive debug console while running rails through foreman in development?

I'm running rails 3.0.6, ruby 1.9.2 and foreman 0.19.0

**Comment by shioyama** [comment]
For anyone wanting to use pry in foreman, [pry-remote](https://github.com/mon-ouie/pry-remote) seems to do the trick for me.

**Comment by jaredbeck** [comment]
> For anyone wanting to use pry in foreman, pry-remote seems to do the trick for me.

Two years later, [byebug][1] also has support for remote debugging. Use `Byebug.start_server` and `byebug -R`. See also Nicholas Gronow's example on SO: https://stackoverflow.com/a/25823241/567762

[1]: https://github.com/deivid-rodriguez/byebug

**Comment by ndbroadbent** [comment]
If anyone else reads this issue, [tmuxinator](https://github.com/tmuxinator/tmuxinator) is a great alternative that also allows you to start multiple processes. It runs them in different tmux "panes" instead of grouping all of the output, so you are able to use a debugger. Foreman is awesome, but I would highly recommend `tmuxinator` for development.

**Comment by erezny** [comment]
If you'd like to run whatever's in your procfile as if you had pasted it into your terminal you can use `run` rather than `start` and then your interactive apps will work fine. You just can't run more than one app in one terminal.

Procfile
```
web: bundle exec rails s
```

```
$ foreman run web
```

**Comment by nijeesh-rently** [comment]
I have been trying out  [overmind](https://github.com/DarthSim/overmind/tree/master) and it great so far.
