### ISSUE TITLE
If pid = 1, foreman should shut down only when Procfile entries shut down

### ISSUE THREAD

**Issue by fmarani** [ddollar/foreman#580]
I am not entirely certain this is a bug, but let me describe what I think the issue is first: I am running foreman inside a docker container, which means it is getting pid = 1. In unix terms, a init process should wait() on all child processes and avoid zombies.

In my project I am running a web and a worker process. The worker process is running, on a specific message, an external program with some gnome/dbus dependencies. dbus-daemon does the double fork trick (or similar) and therefore it becomes child of pid=1 which in this case is foreman.

```
foreman-+-dbus-daemon
        |-dbus-launch
        |-gconfd-2
        |-gunicorn---gunicorn
        |-python-+-Xvfb
        |        |-firefox---42*[{firefox}]
        |        `-6*[{python}]
        `-2*[{foreman}]
```

this is the actual pstree. At some point, my worker tries to shut down selenium/firefox which (i think) tries to shutdown dbus. By looking at foreman source code, it seems that as soon as the wait() call returns it shuts down (i may be wrong here).

This is a problem for me as it brings down the whole container. Anyone had a similar issue?

**Comment by ddollar** [comment]
Foreman generally will refuse changes that are only beneficial to running foreman in production as I am trying to keep the scope narrow as a development tool.

**Comment by elthariel** [comment]
docker-compose is very often used in development env, and this problem seems still relevant
