### ISSUE TITLE
PORT cannot be defaulted

### ISSUE THREAD

**Issue by runningonfumes** [ddollar/foreman#583]
given Procfile

```
test1: echo ${PORT:=3002}
test2: echo ${PORTT:=3003}
```

the output of foreman start is

```
test1.1 | 5000
test2.1 | 3003
```

PORT should be 3002, not 5000

**Comment by ddollar** [comment]
PORT is defined by Foreman so the default won't catch.

**Comment by runningonfumes** [comment]
It's related to https://github.com/ddollar/foreman/issues/175 and https://github.com/ddollar/foreman/issues/167.
So can't it be handled in the same way?

**Comment by ddollar** [comment]
You can set a default port in foreman with `-p` but Foreman itself sets the PORT environment variable for the processes it creates (it is part of the contract) and thus the variable defaulting will always see a value being set.

**Comment by colllin** [comment]
What is the value in foreman specifying a `PORT`?  It's causing a lot of trouble.
