### ISSUE TITLE
foreman.pgk gives error on Mac OS X El Capitan

### ISSUE THREAD

**Issue by 1905** [ddollar/foreman#584]
Installation failed
https://img.bi/#/FidD7D0!E4aLzw3I6YOQbiUgGgJ3yjxQdCsMfwkA1CcQcxSn

**Comment by jeroenvisser101** [comment]
Confirmed :+1:

**Comment by thanh-nguyen** [comment]
Even installing by gem doesn't work. I suspect it's because of the new "rootless" feature of El Capitan. You can't write to /usr/bin/ anymore (got this error: Operation not permitted - /usr/bin/thor)

**Comment by jeroenvisser101** [comment]
I think this would be fixed if we changed `dist/resources/pkg/postinstall` to use the `/usr/local/bin` folder instead, but I'm not quite sure. Also, I have no clue how to test if that works, since I can't seem to figure out how to run the `dist` rake command. I went ahead and created a PR, but I'm not sure if it's of any help. #585

**Comment by fr34k8** [comment]
give us the mount information around /usr/bin

**Comment by ddahan** [comment]
+1, exactly the same problem than @thanh-nguyen

**Comment by vaiwa** [comment]
+1

**Comment by emwalker** [comment]
+1

**Comment by ctharings** [comment]
+1

**Comment by vaiwa** [comment]
https://github.com/strongloop/node-foreman to the rescue!

**Comment by ddollar** [comment]
I doubt I'm going to get around to fixing this myself but if anyone wants to take a swing at a PR I would certainly review/accept.

**Comment by ddollar** [comment]
Fixed by #585

**Comment by ernestocr** [comment]
For anyone that can't get the pkg install (like couldn't for my mbp running Capitan 10.11.1), you can make it work by disabling the rootless feature and **then** installing the pkg, it should work now. Don't forget to enable the rootless feature after installing the pkg.
