### ISSUE TITLE
no implicit conversion from nil to integer (TypeError)

### ISSUE THREAD

**Issue by reggi** [ddollar/foreman#588]
thomas@workstation:flatland$ foreman run -- babel-node www
^C/Users/thomas/.rvm/gems/ruby-2.1.5/gems/foreman-0.78.0/lib/foreman/cli.rb:104:in `exit': no implicit conversion from nil to integer (TypeError)
	from /Users/thomas/.rvm/gems/ruby-2.1.5/gems/foreman-0.78.0/lib/foreman/cli.rb:104:in `run'
	from /Users/thomas/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/thomas/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/thomas/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/thomas/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/thomas/.rvm/gems/ruby-2.1.5/gems/foreman-0.78.0/bin/foreman:7:in `<top (required)>'
	from /Users/thomas/.rvm/gems/ruby-2.1.5/bin/foreman:23:in `load'
	from /Users/thomas/.rvm/gems/ruby-2.1.5/bin/foreman:23:in `<main>'
	from /Users/thomas/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
	from /Users/thomas/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'

**Comment by sahilshekhawat** [comment]
Facing the same error, I think someone should address this.

**Comment by zahidkarim** [comment]
I hit the same problem. I was using foreman and spring. When doing this the initialization is cached with spring. If you are using spring as well try: `spring stop` and the rerun `rails c` should get you back on track

**Comment by ddollar** [comment]
Anyone up for submitting a PR?

**Comment by george-norris-salesforce** [comment]
Have same prob.
