### ISSUE TITLE
service generated by foreman not working on ubuntu 15.04 

### ISSUE THREAD

**Issue by poc7667** [ddollar/foreman#590]
service generated by foreman not working on ubuntu 15.04 

`cd /var/www/sampleApp/current && sudo foreman export upstart /etc/init -a sampleApp`

foreman (0.78.0)

- log

        sudo service sampleApp-web-1 start
        Failed to start sampleApp-web-1.service: Unit sampleApp-web-1.service failed to load: No such file or directory.
        sudo service sampleApp start
        Failed to start sampleApp.service: Unit sampleApp.service failed to load: No such file or directory.

**Comment by chrisvel** [comment]
+1

**Comment by ddollar** [comment]
Anyone want to put together a PR fixing this?
