### ISSUE TITLE
systemd service stops immediately

### ISSUE THREAD

**Issue by Fryie** [ddollar/foreman#591]
When running the exported target with `systemctl start myapp.target`, it automatically quits. It only works if the service is enabled (with `systemctl enable`).

I don't know much about systemd, but from what I understand, it seems that the problem is the `StopWhenUnneeded=true` in the main target config, see [this post](http://superuser.com/a/849009).

**Comment by Fryie** [comment]
I actually even think one should use [PartOf](http://www.freedesktop.org/software/systemd/man/systemd.unit.html#PartOf=) or maybe BindsTo in this situation. Otherwise I don't get the full reloading behaviour when I reload the target e.g. However, my experience with systemd is next to none, so I'd appreciate some more input.

**Comment by ddollar** [comment]
Seems reasonable to me. Please submit the PR.
