### ISSUE TITLE
Making foreman docker pid1 compatible

### ISSUE THREAD

**Issue by emilebosch** [ddollar/foreman#597]
Hi guys,
i am sorta abusing forman to run in docker containers however there are a couple of things blocking which makes this an absolute sexy setup for my multi-process apps.

1. Logging.- In order to log cleanly i need to get rid of the pretty logging that foreman does.  This way i can use the docker logging drivers purely.
2. Reaping children. Pid 1 is responsible for cleaning up zombie processes. Anyone got any experience with this? Or should i just use dumb-init or s6 or something?

Anyone tips or ideas?

**Comment by ddollar** [comment]
Check out github.com/ddollar/init for PID1 in Docker.
