### ISSUE TITLE
Adding date to native logging

### ISSUE THREAD

**Issue by den-chan** [ddollar/foreman#600]
Would there be interest in adding date information to foreman's native log system?

This would involve changing foreman/engine/cli.rb line 60 from:
  output += "#{Time.now.strftime("%H:%M:%S")} #{pad_process_name(name)} | "
To:
  output += "#{Time.now.strftime("%e %b %Y %H:%M:%S")} #{pad_process_name(name)} | "

Sample output (current):
20:44:32 web.1  | message
Sample output (proposed):
4 Feb 2016 20:44:32 web.1  | message

Another option might be ISO8601 time format.

**Comment by ddollar** [comment]
No, let's keep this header short. Foreman generally will refuse changes that are only beneficial to running foreman in production as I am trying to keep the scope narrow as a development tool.
