### ISSUE TITLE
Export foreman workers from Rails app to Upstart fails

### ISSUE THREAD

**Issue by chrisvel** [ddollar/foreman#601]
I want to setup a Rails application running on Puma, on an ubuntu 14.04LTS machine with foreman. 

This is my Procfile

    web: bundle exec puma -t 5:5 -p ${PORT:-3000} -e ${RACK_ENV:-development}
    worker: bundle exec sidekiq
    clock: bundle exec clockwork config/clock.rb

This is the command I am using to generate the service files:

`rvmsudo foreman export upstart /etc/init -a seriapp -u myself`

I am using `sudo service seriapp start` to start the service and as a result the puma server but it fails, usually with a `/bin/sh: 1: exec: bundle: not found`. 

I've read the https://github.com/ddollar/foreman/wiki/Exporting-for-production part but it doesn't clarify what is this PATH you will need to add. 

I did an `echo $PATH`, copied the string from there to the .env file and tried again by adding the GEM path from `gem env`. This time the logs say that `Could not find 'bundler' (>= 0) among 13 total gem(s) (Gem::LoadError)` and obviously it's not a solution to chmod it and set its permissions to something like 777. 

My questions are:

 1. How to make it work ?
 2. Is upstart going to give its place to systemd ? Am I losing my time with upstart?
 3. How would it be automated (Chef) If it's so complicated to set up?

**Comment by ddollar** [comment]
Looks like you need to get your Ruby environment and path in order. Perhaps try an Upstart-related IRC channel?

**Comment by pratik60** [comment]
@ddollar @chrisvel  Facing the same. Do you remember what you did?
