### ISSUE TITLE
.env.local not loaded

### ISSUE THREAD

**Issue by Benjamin-Dobell** [ddollar/foreman#602]
Dotenv was removed as a dependency but its functionality was not fully replicated:
https://github.com/ddollar/foreman/commit/19e9806c4cdf348325fe8312fac827774af4affa

This is similar to another issue open (https://github.com/ddollar/foreman/issues/561), however I'm not after variable interpolation, but simply `.env.local` being loaded as overrides to `.env`.

Using `.env.local` is good practice; if you put it in your `.gitignore` it's a safe place to put secrets (passwords, API keys etc.), in development, which would normally be provided in production as system ENV vars.

**Comment by tisba** [comment]
Too bad :-/ We switched to https://github.com/nickstenning/honcho for now, but still :-/

**Comment by ddollar** [comment]
Yes, we are no longer using a dependency to read these files as we saw numerous dependency hell problems during the time we were using it.
