### ISSUE TITLE
puma: cluster worker not running with foreman

### ISSUE THREAD

**Issue by poc7667** [ddollar/foreman#605]
Currently the foreman not working under it's start command.

It's strange and wierd.

Is there something wrong with my setting?

# Profile

    web: bundle exec puma -e production -C config/puma.rb -e production

# Generate upstart script  with Foreman

      sudo foreman export upstart /etc/init -a sample_web -u app_user 

# Wrong result (cluster worker not running)

Run by `sudo start sample_web_app`

        ➜  init ps aux | grep puma | grep -v grep
        sample_user      18708 95.0 12.2 932652 124540 ?       Ssl  15:40   0:02 puma 2.16.0 (unix:///tmp/puma.sample_web_app.sock,tcp://0.0.0.0:5000) [20160303143446]

# Expected result (working fine)

- Run by `bundle exec puma -e production -C config/puma.rb -e production`
- Run by `cd /etc/init/ && sh sample_web.conf`

        ➜  init ps aux | grep puma | grep -v grep
        sample_user      18964  9.2 14.5 1161336 147908 pts/3  Sl+  15:40   0:03 puma 2.16.0 (unix:///tmp/puma.sample_web_app.sock,tcp://0.0.0.0:8591) [20160303143446]
        sample_user      18974  4.1 21.0 1398328 213560 pts/3  Sl+  15:40   0:01 puma: cluster worker 0: 18964 [20160303143446]

# /etc/init/sample_web.conf (generated by Foreman export command)

    start on starting sample_web
    stop on stopping sample_web
    respawn
    setuid sample_user
    chdir /home/sample_user/workspace/sample_web/releases/20160303143446
    exec bundle exec puma -e production -C config/puma.rb

**Comment by ddollar** [comment]
I'm not sure but try digging through logs to see if you can find what is not starting
