### ISSUE TITLE
Is foreman dead?

### ISSUE THREAD

**Issue by solars** [ddollar/foreman#608]
Hi there,

I'm looking for a daemon handler but it seems as if this project is dead? What's the current status?
Pull request are quite old ..

Thank you

**Comment by aaronshaf** [comment]
@ddollar Perhaps you could add a collaborator?

**Comment by ddollar** [comment]
Not dead, just on very light maintenance. @aaronshaf want to help triage some issues and PRs? I'd be happy to hand out a commit bit.

**Comment by ddollar** [comment]
Tried to get the tests working. Can't figure out the Bundler dance. Gave up. This tool should not be written in Ruby.

**Comment by nruth** [comment]
Did you fix that, as I just tried and the tests are passing? (ruby 2.3.0, bundle install, bundle exec rspec).

**Comment by ddollar** [comment]
Not dead, just lots going on. I'd love some help if anyone is offering. Please ping me at david@convox.com

**Comment by fernandoluizao** [comment]
@ddollar I'm not familiar with the codebase, but I'm willing to help with the maintenance, fixing bugs, merging pull requests...
