### ISSUE TITLE
Multiple runs of foreman export when decreasing processes does not remove extra process files from first export

### ISSUE THREAD

**Issue by willfish** [ddollar/foreman#629]
Our workflow typically involves scaling up/down processes/workers.

Unfortunately, we can't reduce the number of active upstart files because of this change: https://github.com/ddollar/foreman/pull/317.

I began fixing the issue when I discovered that the following test no longer works with my fix:

https://github.com/ddollar/foreman/blob/master/spec/foreman/export/upstart_spec.rb#L41-L51

Essentially, I added (with tests for multiple exports - both decreasing and increasing the number of process files) to `lib/foreman/export/upstart.rb`:

``` ruby
    files_to_clean do |file|
      clean file
    end
```

``` ruby
  def files_to_clean
    Dir["#{location}/#{app}*conf"].each do |file|
      yield file
    end
  end
```

with tests (`spec/foreman/export/upstart_spec.rb`):

``` ruby
    context "with multiple runs" do
      context "when decreasing the number of processes" do
        it "writes out the correct templates" do
          export_for("alpha=2")
          export_for("alpha=1")

          expect(File.read("/tmp/init/app.conf")).to            eq(example_export_file("upstart/app.conf"))
          expect(File.read("/tmp/init/app-alpha.conf")).to      eq(example_export_file("upstart/app-alpha.conf"))
          expect(File.read("/tmp/init/app-alpha-1.conf")).to    eq(example_export_file("upstart/app-alpha-1.conf"))
          expect(File.exist?("/tmp/init/app-alpha-2.conf")).to   be false
        end
      end

      context "when increasing the number of processes" do
        it "writes out the correct templates" do
          export_for("alpha=1")
          export_for("alpha=2")

          expect(File.read("/tmp/init/app.conf")).to            eq(example_export_file("upstart/app.conf"))
          expect(File.read("/tmp/init/app-alpha.conf")).to      eq(example_export_file("upstart/app-alpha.conf"))
          expect(File.read("/tmp/init/app-alpha-1.conf")).to    eq(example_export_file("upstart/app-alpha-1.conf"))
          expect(File.read("/tmp/init/app-alpha-2.conf")).to    eq(example_export_file("upstart/app-alpha-2.conf"))
        end
      end
    end
```

``` ruby
  def export_for(formation)
    engine = Foreman::Engine.new(formation: formation).load_procfile(procfile)
    Foreman::Export::Upstart.new("/tmp/init", engine, options).export
  end
```

The problem is that we don't keep a reference of the files that we've written per app. If we did, then we could use that as a means of determining what files to delete before we export again.

Not sure if anyone with more familiarity of this project has any ideas about an easy solution?

**Comment by patrobinson** [comment]
How we deal with this problem is by storing the config files in a folder that is truncated and updated each time we run `export` and symlink them into `/etc/init`. Then we run `find -L /etc/init -type l -name "<prefix>*.conf"` to find any dangling symlinks

**Comment by willfish** [comment]
That's definitely a good workaround @patrobinson.

So I'm of the opinion that this should be fixed at the source and for all service managers @ddollar. Do you know what's required to fix this? I think it makes sense to keep a filesystem reference yaml file per app somewhere writable to the current user. That way, when we come to export we can load the yaml file and iterate/delete it's contents per export.

**Comment by ddollar** [comment]
I don't want to add a manifest of the export as it's often not run in-place and opens us up to all sorts of cache-invalidation-ish problems.

The names could perhaps be altered to make them more distinct? I'd be willing to review a design/PR towards that end.
