### ISSUE TITLE
Will foreman ever have a 1.0 release?

### ISSUE THREAD

**Issue by patrobinson** [ddollar/foreman#630]
Does foreman use Semantic Versioning? Will foreman ever have a [stable](http://semver.org/#spec-item-4) public API?

I ask because [this](https://github.com/ddollar/foreman/pull/627) PR broke our deployment mechanism silently; while we probably need some integration tests around our deployment code, it was rather surprising to have this kind of non-backwards compatible change. This project is 5 years old now, so is a 1.0 release on the roadmap?

**Comment by ddollar** [comment]
Yes, making plans for a 1.0 now.
