### ISSUE TITLE
Query regarding foreman export

### ISSUE THREAD

**Issue by pratik60** [ddollar/foreman#636]
Hi

I used foreman export via capistrano foreman to generate certain files, which now appear like this 

/etc/init/sites/facebook-dashboard.conf 

```
start on runlevel [2345]
stop on runlevel [!2345]
```

/etc/init/sites/facebook-dashboard-sneakers.conf 
```
start on starting facebook-dashboard
stop on stopping facebook-dashboard
```

/etc/init/sites/facebook-dashboard-sneakers-1.conf
```
start on starting facebook-dashboard-sneakers
stop on stopping facebook-dashboard-sneakers
respawn

env PORT=5000

setuid facebook-dashboard

chdir /var/www/testdash/releases/20160629064953

exec bundle exec rake sneakers:run
```

After export, I am able to run

``` 
sudo start sites/facebook-dashboard
```
, and after this 

```
initctl list | grep "facebook"
sites/facebook-dashboard start/running
sites/facebook-dashboard-sneakers stop/waiting
sites/facebook-dashboard-sneakers-1 stop/waiting
```

I guess the other two are not running, because of my folder structure, and it not being able to recognize it. Do you know the right way if I am to have a subfolder within init? 

Or is the right way to make sure that we can run sudo start facebook-dashboard, after we move the file from init/sites to just init? The problem with init for me was updating this during deployment, as deploy user did not have the right permissions to create/edit files in this folder? But within the sites folder, I was able to give it the right access?

Or am I on a completely wrong track regarding the error, and why it isn't running? Any help would be appreciated :-)

**Comment by ddollar** [comment]
I'm actually not sure either, I don't use upstart much any more. If you get some init files that work for your use case I'd definitely accept a pull request fixing them. Thanks!
