### ISSUE TITLE
.foreman file not being recognised

### ISSUE THREAD

**Issue by MikeRogers0** [ddollar/foreman#637]
I recently upgraded from foreman 0.78.0 to 0.82.0 & my `.foreman` file seems to not be affecting the `foreman start` command any more. Here is my `Procfile` / `.foreman` files:

`Procfile` :

```
web: bundle exec puma -C config/puma.rb
sidekiq: env DATABASE_POOL=${SIDEKIQ_CONCURRENCY:-10} bundle exec sidekiq
```

`.foreman` :

```
concurrency: test=1,web=1,sidekiq=0
env: .env,.env.local
port: 3000
```

If this is a bug, if you can point me in the right direction I'm happy to attempt to fix :)

**Comment by ddollar** [comment]
Sounds like it might be a bug. Is the entire .foreman file not working?

**Comment by MikeRogers0** [comment]
Hi!
It looks like the entire .foreman file isn't being loaded. I'm happy to setup an example repo if that'll help you debug?

**Comment by scopej** [comment]
I ran into this same issue, seems like the config file format changed and now concurrency: should be formation:
