### ISSUE TITLE
Is foreman should start after server reboot using systemd export?

### ISSUE THREAD

**Issue by slbug** [ddollar/foreman#638]

**Comment by ddollar** [comment]
Could you please re-ask your question with a bit more detail?

**Comment by slbug** [comment]
I'm using capistrano to deploy app on ubuntu 16.04. there is command ```cap foreman:export```
it creates files for systemd. But after server restart (e.g. sudo reboot) it does not start app. I have to do it manually

**Comment by stevendaniels** [comment]
If I recall, you need to run `cap foreman:export` as a root user in order create a systemd startup app. Did you try running that command with sudo?

**Comment by koenpunt** [comment]
`cap foreman:export` isn't part of this repo, but of [`capistrano-foreman`](https://github.com/hyperoslo/capistrano-foreman)
