### ISSUE TITLE
Export command : -t param is defined twice

### ISSUE THREAD

**Issue by n-rodriguez** [ddollar/foreman#639]
Once for the template option : https://github.com/ddollar/foreman/blob/master/lib/foreman/cli.rb#L53
Once for the timeout option : https://github.com/ddollar/foreman/blob/master/lib/foreman/cli.rb#L55

**Comment by fernandoluizao** [comment]
Get caught by this one...tried to specify timeout when exporting to systemd with _-t_ doesn't works, however, it works with _--timeout_.

**Comment by n-rodriguez** [comment]
Hi there! Any news?

**Comment by n-rodriguez** [comment]
Hi there! Any news?
