### ISSUE TITLE
Why 3 upstart scripts?

### ISSUE THREAD

**Issue by jjb** [ddollar/foreman#641]
Why does the upstart export produce 3 scripts? I can't find any other examples of multi-script upstart configurations. Also, the app.conf and app-server.conf scripts are very confusing to me, they don't specify the location of the process.

After getting my answer I'll be happy to add more detail to the documentation. Thanks!

**Comment by ddollar** [comment]
I honestly no longer remember. If there's a better way to do this in upstart I'd be happy to take a PR to that exporter. Cheers!
