### ISSUE TITLE
Backgrounded process leads to stop foreman

### ISSUE THREAD

**Issue by rahul100885** [ddollar/foreman#65]
Hi,

I am using rails 2.3.5 with one of my old project where lots of process are running with rails application.

Out of that, one of the command is "rake ts:start". Which start the sphinx server (Thinking-sphinx gem).

This command start sphinx daemon and come out on terminal.

Well but if I use it with foreman it start the all server but after starting sphinx server kill all servers and foreman also.

If I remove  "rake ts:start" every thing is working fine.

**Comment by benjiwheeler** [comment]
Is there any way around this? I'm finding foreman incredibly useful, but it would be even more useful to be able to use it to run commands that are supposed to daemonize.
