### ISSUE TITLE
Foreman OS Mirrors

### ISSUE THREAD

**Issue by elJoeyJojo** [ddollar/foreman#651]
Hello,

Not sure where to get help for this but I have a working Foreman Provisioning Server that is working but every VM I provision, it goes and gets the ISO/install files to the online repos and I'd like to change that so that it gets it from my server. Kinda new at Foreman. Can anyone help me or point me in the right the direction?

Thanks

Joey

**Comment by mmoll** [comment]
This is about the "other" foreman project (http://theforeman.org/), please close this.
