### ISSUE TITLE
Export To Systemd

### ISSUE THREAD

**Issue by jasonivers** [ddollar/foreman#664]
When I have a .env file, foreman is ending up with ExecStart on the Environment line, like this:

`
Environment="PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games" "RAILS_ENV=uat" "RACK_ENV=uat" ExecStart=/bin/bash -lc 'bash -lic 'bin/sidekiq''
`

This breaks restarting it.  It should be:

`
Environment="PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games" "RAILS_ENV=uat" "RACK_ENV=uat"
ExecStart=/bin/bash -lc 'bash -lic 'bin/sidekiq''
`

**Comment by timurb** [comment]
@jasonivers I think you've mistyped the "it should be" part.
It should be something like the following instead:
```
Environment=PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
Environment=RAILS_ENV=uat
Environment=RACK_ENV=uat
ExecStart=/bin/bash -lc 'bash -lic bin/sidekiq'
```

I see exactly the same issue for the few recent days.

**Comment by timurb** [comment]
I guess this commit introduced regression: https://github.com/ddollar/foreman/commit/c7edf6490b6ccf02df2de9e03d76b1fb1a8df63b

No idea if this one contributed to that too: https://github.com/ddollar/foreman/pull/652

**Comment by ddollar** [comment]
Anyone up for writing a patch and a test case so this doesn't regress again?

**Comment by timurb** [comment]
I can take a look. Any idea how to write a test for this?

24 янв 2017 г. 6:19 PM пользователь "David Dollar" <notifications@github.com>
написал:

**Comment by yelhouti** [comment]
Thanks guys for the great work, you might want to remove the gem 0.83 since you removed the release from git

**Comment by dunyakirkali** [comment]
When can we expect this to be released?

**Comment by jasonivers** [comment]
Thank you for coding the fix... will it be released any time soon?

**Comment by rilian** [comment]
thank you so much 👍
