### ISSUE TITLE
losing color when directing to file

### ISSUE THREAD

**Issue by chrisdobler** [ddollar/foreman#666]
if I direct the output to a file like this:

`foreman start -f Procfile.dev >> ~/Library/logs/monitor.log 2>&1`

I lose the colors. How can I get the colors in the logfile?

**Comment by ddollar** [comment]
Pretty sure this is as designed. Most folks dont want ANSI colors in their logfiles. Foreman does this by detecting the tty-ness of the output so you could possibly rig something up with tee/shell to keep color in your logfiles.
