### ISSUE TITLE
Set port to Foreman in Procfile

### ISSUE THREAD

**Issue by PedroPauloML** [ddollar/foreman#667]
In a previous project, the port of Foreman was same the port of rails (3000), but now the Foreman is using the port 5000.

How I set the port 3000 to default port of Foreman?

**Comment by toobulkeh** [comment]
Check your Procfile in the root directory.

It may look like:
```
web: bundle exec puma -p $PORT -C ./config/puma.rb
```

The `-p $PORT` portion is setting the Port to whatever the ENV Variable PORT is.

We use dotenv, which pulls a config from the `.env` file in the root directory.
```
PORT=3000
```

**Comment by ddollar** [comment]
You can use `-p 3000`. This behavior has been the same for a long time so maybe something else changed?

**Comment by sergey-alekseev** [comment]
Previously on Rails 4:  
>Rails 4.2.11.1 application starting in development on http://localhost:3000  

After the upgrade to Rails 5:  
>Rails 5.0.7.2 application starting in development on http://localhost:5000  

The change is caused by https://github.com/rails/rails/commit/306c14c41135dc8d308967821d0bb26cf4bb7ecd:  
> `rails server` will now honour the `PORT` environment variable
