### ISSUE TITLE
Direct TTY to specific process?

### ISSUE THREAD

**Issue by toobulkeh** [ddollar/foreman#670]
Is there a way to direct the active TTY to a specific process?

We regularly use Foreman in development and have the need to pry/byebug debug them often.

Thanks

**Comment by doits** [comment]
second that. one could redirect the tty to the process running the debugger, in my case the development web server. could be a command line switch/config option.

**Comment by ddollar** [comment]
Sorry, Foreman is an output-only tool right now.
