### ISSUE TITLE
process in Procfile exiting with 0 kills all sibling processes

### ISSUE THREAD

**Issue by Judahmeek** [ddollar/foreman#676]
How can I have a process defined in the Procfile exit with 0 and all other processes defined in the Procfile keep running?

```
16:03:14 webpack-style-bundle.1  | Done in 12.72s.
16:03:15 webpack-style-bundle.1  | exited with code 0
16:03:15 system                  | sending SIGTERM to all processes <~ DO NOT WANT
16:03:15 webpack-server-bundle.1 | terminated by SIGTERM
16:03:15 webpack-hmr.1           | terminated by SIGTERM
```

**Comment by ddollar** [comment]
Unfortunately this is not possible with Foreman. All of the processes die when one dies.

**Comment by xahon** [comment]
@ddollar no. I have react and electron in my procfile. When electron dies react still alive  

> 1:54:25 PM react.1    |  > electron-with-create-react-app@0.1.0 start /home/***/dev/***
> 1:54:25 PM react.1    |  > react-app-rewired start
> 1:54:26 PM react.1    |  Starting the development server...
> 1:54:27 PM electron.1 |  starting electron
> 1:54:31 PM react.1    |  Compiled successfully!
> 1:54:31 PM react.1    |  The app is running at:
> 1:54:31 PM react.1    |    http://localhost:5000/
> 1:54:31 PM react.1    |  Note that the development build is not optimized.
> 1:54:31 PM react.1    |  To create a production build, use yarn run build.
> 1:54:31 PM react.1    |  Compiling...
> 1:54:32 PM react.1    |  Compiled successfully!
> [DONE] Killing all processes with signal  null
> 1:54:41 PM electron.1 Exited Successfully
> ^C[WARN] Interrupted by User

As you can see electron exits but react doesn't. I need to interrupt manually
