### ISSUE TITLE
Foreman gets stuck

### ISSUE THREAD

**Issue by levicole** [ddollar/foreman#680]
**What's happening:**

I'm using Foreman to run resque, webpack and puma. There are cases where it seems like Foreman gets stuck after Webpack has compiled. When this happens, any request to my rails app is not processed. It seems like it happens at random. I've not been able to consistently get this to happen.

When it _does_ happen, I'm able to get things running by simply writing to a javascript file to trigger Webpack to recompile. Once webpack recompiles, my rails app starts accepting requests again.

I've switched from using foreman to your Go fork, forego. It works perfectly, but I thought I'd still file the issue.

This could be related to my environment, so feel free to just close if you feel like that's the case.

**This is my Procfile**

```
web: bundle exec puma -C config/puma.rb
worker: env QUEUE=* VERBOSE=1 bundle exec rake resque:work
webpack: env UV_THREADPOOL_SIZE=128 webpack --watch --progress --colors --display-reasons --config webpack.dev.config.js
```

**Comment by megalithic** [comment]
@levicole i've linked a similar issue back over to [webpacker](https://github.com/rails/webpacker/issues/1051)

**Comment by megalithic** [comment]
@ddollar is there a proper way to debug this sort of thing? i'm having the same issue as per my linked issue.

**Comment by andrewmcodes** [comment]
@levicole is this still an issue?

**Comment by levicole** [comment]
It's been quite a while since I've used foreman.

I've since switched to using `heroku local` which I believe uses forego instead and that seems to work better. The down side is that for debugging one must use a remote debugger, but not a deal breaker for me.

**Comment by andrewmcodes** [comment]
@levicole nice. If it is no longer an issue for you - would you be interested in closing this? Just trying to help out the maintainer here 😁

**Comment by levicole** [comment]
Happy to! Sorry I haven't before this.
