### ISSUE TITLE
Restart stopped processes?

### ISSUE THREAD

**Issue by mikeyp** [ddollar/foreman#685]
I'm looking at using Foreman to manage local development environments for a small team, but some of our background workers are designed to exit after a set amount of time has elapsed. In production, this is managed by something like upstart, supervisord, etc, but I'd prefer to use a more lightweight tool, like Foreman for local development.

Is it possible to configure Foreman to restart a stopped worker instead of exiting?

**Comment by andrewmcodes** [comment]
@mikeyp are you still looking for an answer to this question?

**Comment by mikeyp** [comment]
No, I'm no longer using Foreman, thanks for asking.
