### ISSUE TITLE
Rails 6 compressibility  

### ISSUE THREAD

**Issue by AirWick219** [ddollar/foreman#743]
I was wondering what is the plan for foreman to be Rails 6 comparable ??? 

As more and more people upgrade to Rails 6, they will run into this issue

<img width="428" alt="Screen Shot 2019-10-08 at 2 25 54 PM" src="https://user-images.githubusercontent.com/5618294/66426506-96473400-e9d7-11e9-94d5-c9e98c82e4b9.png">
<img width="419" alt="Screen Shot 2019-10-08 at 2 26 35 PM" src="https://user-images.githubusercontent.com/5618294/66426570-bd056a80-e9d7-11e9-8335-5f486e122629.png">
<img width="453" alt="Screen Shot 2019-10-08 at 2 26 40 PM" src="https://user-images.githubusercontent.com/5618294/66426571-bd056a80-e9d7-11e9-973b-18637a51ca74.png">

Since foreman locks down `'thor', '~> 0.19.1'` [here](https://github.com/ddollar/foreman/blob/master/foreman.gemspec#L20) and 
Rails 6 has it `"thor", ">= 0.20.3", "< 2.0"` [here](https://github.com/rails/rails/blob/v6.0.0/railties/railties.gemspec#L40) . 

I can submit a PR to address this.

**Comment by ddollar** [comment]
https://github.com/ddollar/foreman/wiki/Don't-Bundle-Foreman
