### ISSUE TITLE
/usr/bin/env: foreman: No such file or directory

### ISSUE THREAD

**Issue by millisami** [ddollar/foreman#76]
Well, when I try to export the upstart file, it says the following error:

```
$ rvmsudo foreman export upstart /etc/init -a myapp -u deploy -f ./Procfile.production
/usr/bin/env: foreman: No such file or directory
```

**Comment by lichtamberg** [comment]
How did you fix it? I have the same problem

**Comment by kolosek** [comment]
@h0jeZvgoxFepBQ2C 3 years have passed, but a solution that worked for me is installing ruby-foreman:
`sudo apt install ruby-foreman`

And restarting the machine.

**Comment by kolosek** [comment]
Stumble upon my own answer, nice!
