### ISSUE TITLE
Add a Changelog

### ISSUE THREAD

**Issue by nirvdrum** [ddollar/foreman#84]
It'd be very helpful to track the status of the project via a changelog.  While the git history seems pretty linear, it's not always immediately obvious what a particular change means for an end user.  An annotated Changelog would go a long way in helping with that.

**Comment by fernandoluizao** [comment]
The changelog is no longer being updated? Not even tags in the repo?

**Comment by ddollar** [comment]
Thanks for your inquiry. The Changelog has been updated.
