### ISSUE TITLE
Exported upstart script doesn't seem to always stop correctly?

### ISSUE THREAD

**Issue by untoldone** [ddollar/foreman#97]
For example, if there is a procfile line 'clock: source ../.bash_profile; ruby ./scheduler.rb'. (The sourcing is done to use RVM). 'rvmsudo foreman export upstart /etc/init -u brainstem' is used to export. The export command  generates a file, brainstem-clock-1.conf, that contains:

start on starting brainstem-clock
stop on stopping brainstem-clock
respawn

exec su - brainstem -c 'cd /home/brainstem/brainstem; export PORT=5200; source ../.bash_profile; ruby ./scheduler.rb >> /var/log/brainstem/clock-1.log 2>&1

When 'stop brainstem' is run upstart just stops the shell session that is started by su but the child thin processes stick around.

**Comment by gamb** [comment]
Was this never get merged?? 2015 - having the same issue.

**Comment by dmishh** [comment]
@msaffitz :+1:
